# openshift-oauth-client-authorizer Development

Development can be performed in the `odo` OpenShift developer CLI or building with OpenShift build configs.
An OpenShift cluster with cluster-admin is required for `odo` development.
https://developers.redhat.com/products/codeready-containers/overview[CodeReady Containers] is recommended for local development.
An Ansible test suite is available for functional testing.

## Development with `odo`

Use of `odo` is recommended for fast iterative development.
`odo` simplifies the build/deploy process and avoids creating unnecessary build artifacts during the development process.

. Install the `odo` developer CLI as described in the OpenShift documentation:
https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html[Installing odo]

. Create custom resource definition for clusterkopfpeerings.kopf.dev:
+
---------------------------------------------
oc apply -f clusterkopfpeerings.kopf.dev.yaml
---------------------------------------------

. Create custom resource definition and cluster role from the provided helm chart:
+
---------------------------------------------------------------------
helm template helm --include-crds --set deploy=false | oc apply -f -
---------------------------------------------------------------------

. Create a project for development using `odo`:
+
----------------------------------------------------
oc adm new-project openshift-oauth-client-authorizer
odo project set openshift-oauth-client-authorizer
----------------------------------------------------

. Grant privileges for cluster role to default service account:
+
-----------------------------------------------------------------------------------
oc adm policy add-cluster-role-to-user openshift-oauth-client-authorizer -z default
-----------------------------------------------------------------------------------

. Setup `odo` from the provided `devfile.yaml`:
+
---------------------------------
odo create --devfile devfile.yaml
---------------------------------

. Use `odo push` to push code into the odo container:
+
--------
odo push
--------

. Run tests with Ansible:
+
-----------------------------------
ansible-playbook test/playbook.yml
-----------------------------------

. Cleanup
+
Remove `odo` component
+
----------------------------------------------------
odo delete --force openshift-oauth-client-authorizer
----------------------------------------------------
+
Remove ClusterRoleBinding
+
----------------------------------------------------------------------------------------
oc adm policy remove-cluster-role-from-user openshift-oauth-client-authorizer -z default
----------------------------------------------------------------------------------------

## Development with OpenShift build

The OpenShift build process is a bit slower for development but has the advantage of being a bit closer to a normal deployment.
It is often best to iterate development using `odo` and also test with an OpenShift build and deployment prior to opening a pull request.

. Create a project for development using `oc`:
+
------------------------------------------------
oc new-project openshift-oauth-client-authorizer
------------------------------------------------

. Process OpenShift build template to create BuildConfig and ImageStream:
+
---------------------------------------------------------
oc process --local -f build-template.yaml | oc apply -f -
---------------------------------------------------------

. Build image from local source:
+
----------------------------------------------------------------------
oc start-build openshift-oauth-client-authorizer --from-dir=. --follow
----------------------------------------------------------------------

. Deploy from build image
+
--------------------------------------------------------------------------------
helm template helm --include-crds \
--set=image.tagOverride=- \
--set=image.repository=$(oc get imagestream openshift-oauth-client-authorizer -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}') \
| oc apply -f -
--------------------------------------------------------------------------------

. Run tests with Ansible:
+
-----------------------------------
ansible-playbook test/playbook.yml
-----------------------------------

. Cleanup
+
Remove resources created from the helm template:
+
--------------------------------------------------
helm template helm --include-crds | oc delete -f -
--------------------------------------------------
+
Remove BuildConfig and ImageStream:
+
----------------------------------------------------------
oc process --local -f build-template.yaml | oc delete -f -
----------------------------------------------------------
