{{- if .Values.deploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshift-oauth-client-authorizer.name" . }}
  namespace: {{ include "openshift-oauth-client-authorizer.namespaceName" . }}
  labels:
    {{- include "openshift-oauth-client-authorizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openshift-oauth-client-authorizer.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "openshift-oauth-client-authorizer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: manager
          env:
          - name: TIMER_INTERVAL
            value: "{{ .Values.timerInterval }}"
          image: {{ include "openshift-oauth-client-authorizer.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          ports:
          - name: metrics
            containerPort: 8000
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "openshift-oauth-client-authorizer.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
