{{- if and .Values.deploy .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshift-oauth-client-authorizer.serviceAccountName" . }}
  namespace: {{ include "openshift-oauth-client-authorizer.namespaceName" . }}
  labels:
    {{- include "openshift-oauth-client-authorizer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
