apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oauthclientauthorizationautomations.pfe.redhat.com
spec:
  group: pfe.redhat.com
  scope: Namespaced
  names:
    plural: oauthclientauthorizationautomations
    singular: oauthclientauthorizationautomation
    kind: OAuthClientAuthorizationAutomation
    shortNames: []
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          OAuthClientAuthorizationAutomation configures automatic creation of OAuthClientAuthorizations for a service account.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              generateName:
                type: string
                maxLength: 57
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*)?$
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
          spec:
            type: object
            required:
            - serviceAccountName
            properties:
              serviceAccountName:
                description: >-
                  Name of service account for which to create authorizations.
                type: string
              scopes:
                description: >-
                  Scopes to use for OAuthClientAuthorization objects.
                type: array
                items:
                  type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
